# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LampUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LampUIKit

  target 'LampUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LampUIKitUITests' do
    # Pods for testing
  end

pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'ARCL'
end
